# Generated by Django 5.2.10 on 2026-01-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organization_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('TWILIO', 'Twilio'), ('AFRICASTALKING', 'AfricaTalking'), ('META_WHATSAPP', 'Meta WhatsApp Cloud')], max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('api_key_or_token', models.TextField()),
                ('sender_id_or_number', models.CharField(max_length=100)),
                ('enabled_channels', models.JSONField(default=list, help_text="['SMS', 'WHATSAPP']")),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('FLUTTERWAVE', 'Flutterwave'), ('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal')], max_length=32)),
                ('label', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=255)),
                ('_secret_key', models.TextField(db_column='secret_key')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled_regions', models.JSONField(default=list, help_text="List of region codes e.g. ['KE', 'UG']")),
                ('active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Ujenzi Marketplace', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='platform/branding/')),
                ('support_email', models.EmailField(default='support@ujenzi.com', max_length=254)),
                ('support_phone', models.CharField(default='+254 700 000000', max_length=32)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('default_region', models.CharField(default='KE', max_length=10)),
                ('active_languages', models.JSONField(default=list, help_text="List of language codes e.g. ['en', 'sw']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('enabled_regions', models.JSONField(blank=True, default=list)),
                ('enabled_for_orgs', models.ManyToManyField(blank=True, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_override', models.ImageField(blank=True, null=True, upload_to='org/branding/')),
                ('primary_color', models.CharField(default='#0052cc', max_length=7)),
                ('secondary_color', models.CharField(default='#f4f5f7', max_length=7)),
                ('procurement_rules', models.JSONField(blank=True, default=dict)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization')),
            ],
        ),
    ]
