# Generated by Django 5.2.10 on 2026-02-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 code e.g. USD, EUR, TZS', max_length=10, unique=True)),
                ('currency_name', models.CharField(help_text='e.g. US Dollar', max_length=100)),
                ('symbol', models.CharField(help_text='e.g. $, €, KSh', max_length=10)),
                ('rate_to_default', models.DecimalField(decimal_places=6, help_text='How many units of this currency equal 1 unit of the default currency', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency_code'],
            },
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='primary_color',
            field=models.CharField(default='#FF6B2B', help_text='Brand primary hex color', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='secondary_color',
            field=models.CharField(default='#1A1A2E', help_text='Brand secondary hex color', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short platform tagline', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='active_languages',
            field=models.JSONField(default=list, help_text="e.g. ['en', 'sw']"),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
