# Generated by Django 5.2.10 on 2026-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0002_currencyrate_platformsettings_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2/3 code e.g. KE, UG, TZ', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, help_text='e.g. 🇰🇪', max_length=10)),
                ('phone_prefix', models.CharField(blank=True, help_text='e.g. +254', max_length=10)),
                ('default_currency', models.CharField(blank=True, help_text='ISO 4217 code', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="The platform's primary country")),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
