# Generated by Django 5.2.10 on 2026-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0003_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("EXCHANGE_RATE_API", "ExchangeRate-API"),
                            ("EXCHANGERATE_HOST", "Exchangerate.host"),
                            ("OPEN_EXCHANGE_RATES", "Open Exchange Rates"),
                            ("CUSTOM", "Custom API"),
                        ],
                        default="EXCHANGE_RATE_API",
                        max_length=32,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Primary Exchange Rate API", max_length=100
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="The API endpoint URL (e.g. https://v6.exchangerate-api.com/v6/KEY/latest/USD)"
                    ),
                ),
                (
                    "_api_key",
                    models.TextField(blank=True, db_column="api_key", null=True),
                ),
                (
                    "mapping_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping for JSON response. Example: {'rates_key': 'conversion_rates', 'date_key': 'time_last_update_utc'}",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Exchange Rate API Config",
                "verbose_name_plural": "Exchange Rate API Configs",
            },
        ),
    ]
