# Generated by Django 5.2.10 on 2026-02-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0006_data_migration_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
