# Generated by Django 4.2.16 on 2026-04-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0007_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower values appear first'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='instructions',
            field=models.TextField(blank=True, help_text='Short customer-facing instructions for this payment method'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use as the default payment method where applicable'),
        ),
    ]
