# Generated by Django 5.2.10 on 2026-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0009_exchange_rate_config_frankfurter_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerateconfig",
            name="base_url",
            field=models.URLField(
                help_text="The API endpoint URL (e.g. https://api.frankfurter.dev/v1/latest?base=BASE)"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerateconfig",
            name="label",
            field=models.CharField(
                default="Primary Exchange Rate Provider", max_length=100
            ),
        ),
    ]
