# Generated by Django 5.2.10 on 2026-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0010_alter_exchangerateconfig_base_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="rate_to_default",
            field=models.DecimalField(
                decimal_places=6,
                help_text="How many units of the default currency equal 1 unit of this currency",
                max_digits=18,
            ),
        ),
    ]
