# Generated by Django 5.2.10 on 2026-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('VENDOR', 'Vendor'), ('CONTRACTOR', 'Contractor'), ('ADMIN', 'Admin')], default='BUYER', max_length=20),
        ),
    ]
