# Generated by Django 5.2.10 on 2026-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROJECT_OWNER', 'Project Owner'), ('VENDOR', 'Vendor'), ('CONTRACTOR', 'Contractor'), ('INVESTOR', 'Investor'), ('GOVERNMENT', 'Government'), ('ADMIN', 'Admin')], default='PROJECT_OWNER', max_length=20),
        ),
    ]
