# Generated by Django 4.2.16 on 2026-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of roles assigned to the user'),
        ),
    ]
