# Generated by Django 5.2.10 on 2026-02-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROJECT_OWNER", "Project Owner"),
                    ("VENDOR", "Vendor"),
                    ("CONTRACTOR", "Contractor"),
                    ("INVESTOR", "Investor"),
                    ("GOVERNMENT", "Government"),
                    ("COURIER", "Courier"),
                    ("ADMIN", "Admin"),
                ],
                default="PROJECT_OWNER",
                max_length=20,
            ),
        ),
    ]
