# Generated by Django 5.2.10 on 2026-02-22 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 22, 10, 17, 59, 980843, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="hub_type",
            field=models.CharField(
                choices=[
                    ("SITE", "Construction Site"),
                    ("WAREHOUSE", "Warehouse / Depot"),
                    ("OFFICE", "Operational Office"),
                    ("RETAIL", "Retail Point"),
                    ("RESIDENTIAL", "Residential / Private"),
                ],
                default="SITE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="Kenya", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(
                help_text="e.g. Site Alpha, Warehouse B", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
