# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_address_created_at_address_hub_type_address_latitude_and_more",
        ),
        ("platform_settings", "0007_location_latitude_location_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "verbose_name": "Delivery Address",
                "verbose_name_plural": "Delivery Addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="buyerprofile",
            options={
                "verbose_name": "Buyer Preferences",
                "verbose_name_plural": "Buyer Preferences",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(max_length=255, verbose_name="Street Address"),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Apartment, Suite, Floor"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City / Town"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="Kenya", max_length=100, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Added On"),
        ),
        migrations.AlterField(
            model_name="address",
            name="hub_type",
            field=models.CharField(
                choices=[
                    ("SITE", "🏗️ Construction Site"),
                    ("WAREHOUSE", "📦 Warehouse / Depot"),
                    ("OFFICE", "🏢 Office / Worksite"),
                    ("RETAIL", "🛒 Retail Store"),
                    ("RESIDENTIAL", "🏠 Home / Residential"),
                ],
                default="SITE",
                max_length=20,
                verbose_name="Location Type",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Set as Default Address"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(
                help_text="Give this address a name, e.g. 'Site Alpha', 'Home Office'",
                max_length=100,
                verbose_name="Address Name",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal / ZIP Code"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_province",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="State / Province / County"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Belongs To",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="delivery_instructions",
            field=models.TextField(
                blank=True,
                help_text="Any notes for delivery drivers, e.g. 'Gate code: 1234'",
                verbose_name="Special Delivery Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="preferred_region",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Preferred Delivery Region"
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Created"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, verbose_name="About Organization"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Organization Name"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL Slug"),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="About Me"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="platform_settings.location",
                verbose_name="Primary Location",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROJECT_OWNER", "Project Owner / Client"),
                    ("VENDOR", "Material Supplier"),
                    ("CONTRACTOR", "Construction Professional"),
                    ("INVESTOR", "Project Investor"),
                    ("GOVERNMENT", "Government Agency"),
                    ("COURIER", "Logistics Partner"),
                    ("ADMIN", "System Administrator"),
                ],
                default="PROJECT_OWNER",
                max_length=20,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Additional roles assigned to the user",
                verbose_name="Additional Roles",
            ),
        ),
    ]
