# Generated by Django 4.2.16 on 2026-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_address_options_alter_buyerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROJECT_OWNER', 'Project Owner / Client'), ('VENDOR', 'Material Supplier'), ('CONTRACTOR', 'Construction Professional'), ('INVESTOR', 'Project Investor'), ('PROPERTY_MANAGER', 'Property Manager'), ('GOVERNMENT', 'Government Agency'), ('COURIER', 'Logistics Partner'), ('ADMIN', 'System Administrator')], default='PROJECT_OWNER', max_length=20, verbose_name='Account Type'),
        ),
    ]
