# Generated by Django 4.2.16 on 2026-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROJECT_OWNER', 'Project Owner / Client'), ('VENDOR', 'Material Supplier'), ('CONTRACTOR', 'Construction Professional'), ('INVESTOR', 'Project Investor'), ('PROPERTY_MANAGER', 'Property Manager'), ('REAL_ESTATE_AGENT', 'Real Estate Agent'), ('SURVEYOR', 'Surveyor / Valuer'), ('GOVERNMENT', 'Government Agency'), ('COURIER', 'Logistics Partner'), ('ADMIN', 'System Administrator')], default='PROJECT_OWNER', max_length=20, verbose_name='Account Type'),
        ),
    ]
