# Generated by Django 5.2.10 on 2026-01-31 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'taxonomy_type': 'MATERIAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='taxonomy.category'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
