# Generated by Django 5.2.10 on 2026-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_regions',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['NAIROBI', 'MOMBASA']"),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OUT_OF_STOCK', 'Out of Stock'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20),
        ),
    ]
