# Generated by Django 5.2.10 on 2026-01-31 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_is_active_product_delivery_regions_and_more'),
        ('taxonomy', '0001_initial'),
        ('vendors', '0003_alter_vendor_options_vendor_average_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Image description for accessibility', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image shown in listings')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which images are displayed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.TextField(blank=True, help_text='Common applications or use cases'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand or manufacturer name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for bulk orders', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_threshold',
            field=models.IntegerField(blank=True, help_text='Minimum quantity for bulk pricing', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.TextField(blank=True, help_text="Certifications (e.g., 'KEBS Certified, ISO 9001')"),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Dimensions (L x W x H in cm)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time in days', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='For perishable materials', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)'),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_instructions',
            field=models.TextField(blank=True, help_text='Special handling or storage instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured products'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_composition',
            field=models.TextField(blank=True, help_text='Material composition or ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.IntegerField(blank=True, help_text='Maximum quantity per order', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model/SKU number', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(blank=True, help_text="Quality grade (e.g., 'Grade A', 'Premium')", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_special_handling',
            field=models.BooleanField(default=False, help_text='Fragile, hazardous, or special care needed'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping weight (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief product summary for listings', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Technical specs as key-value pairs'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(blank=True, help_text="Warranty period (e.g., '12 months', '2 years')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight per unit (kg)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Product name (e.g., 'Dangote Cement 50kg')", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(help_text="Unit of measurement (e.g., 'bag', 'ton', 'piece')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status'], name='catalog_pro_vendor__bf2425_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='catalog_pro_product_c9ec4d_idx'),
        ),
    ]
