# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage_alter_product_options_and_more"),
        ("taxonomy", "0002_alter_category_options_alter_category_active_and_more"),
        ("vendors", "0006_vendor_location_text_alter_vendor_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["display_order", "uploaded_at"],
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="applications",
            field=models.TextField(
                blank=True,
                help_text="Common uses and applications",
                verbose_name="Recommended Applications",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Regular price per unit",
                max_digits=12,
                verbose_name="Standard Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="Manufacturer or brand name",
                max_length=100,
                verbose_name="Brand / Manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bulk_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted price for large orders",
                max_digits=12,
                null=True,
                verbose_name="Bulk Order Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bulk_threshold",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum quantity to qualify for bulk price",
                null=True,
                verbose_name="Bulk Quantity Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"taxonomy_type": "MATERIAL"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="taxonomy.category",
                verbose_name="Product Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="certifications",
            field=models.TextField(
                blank=True,
                help_text="e.g. 'KEBS Certified, ISO 9001, CE Marked'",
                verbose_name="Certifications & Standards",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Color / Finish"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Added On"),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_regions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="e.g. ['NAIROBI', 'MOMBASA', 'KISUMU']",
                verbose_name="Delivery Locations",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Full product description with details",
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="L x W x H in centimeters",
                max_length=100,
                verbose_name="Dimensions (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="estimated_delivery_days",
            field=models.IntegerField(
                blank=True,
                help_text="Typical delivery time",
                null=True,
                verbose_name="Estimated Delivery Time (days)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="For perishable or time-sensitive materials",
                null=True,
                verbose_name="Expiry / Best Before Date",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Key features, one per line",
                verbose_name="Product Features",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="handling_instructions",
            field=models.TextField(
                blank=True,
                help_text="Special storage or handling requirements",
                verbose_name="Handling Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show in featured products section",
                verbose_name="Featured Product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new_arrival",
            field=models.BooleanField(
                default=False, verbose_name="Mark as New Arrival"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_on_sale",
            field=models.BooleanField(default=False, verbose_name="Currently On Sale"),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturing_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of Manufacture"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="material_composition",
            field=models.TextField(
                blank=True,
                help_text="What it's made of",
                verbose_name="Material Composition",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_order_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum quantity per order (leave blank for unlimited)",
                null=True,
                verbose_name="Maximum Order Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Search keywords, comma-separated",
                max_length=500,
                verbose_name="Search Keywords",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_order_quantity",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Minimum Order Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.CharField(
                blank=True,
                help_text="Model or SKU number",
                max_length=100,
                verbose_name="Model / SKU Number",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Product name as customers will see it",
                max_length=255,
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quality_grade",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Grade A', 'Premium', 'Standard'",
                max_length=50,
                verbose_name="Quality Grade",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="requires_special_handling",
            field=models.BooleanField(
                default=False,
                help_text="Check if fragile, hazardous, or needs special care",
                verbose_name="Requires Special Handling",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shipping weight if different from unit weight",
                max_digits=10,
                null=True,
                verbose_name="Shipping Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief summary for product listings",
                max_length=500,
                verbose_name="Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name",
                max_length=300,
                verbose_name="URL Slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "📝 Draft - Not Published"),
                    ("ACTIVE", "✅ Active - Available for Purchase"),
                    ("OUT_OF_STOCK", "📭 Temporarily Out of Stock"),
                    ("DISABLED", "🚫 Disabled - Not Available"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Product Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Current Stock Level",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="technical_specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Technical details as key-value pairs",
                verbose_name="Technical Specifications",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                help_text="How it's sold, e.g. 'bag', 'ton', 'piece', 'meter'",
                max_length=50,
                verbose_name="Unit of Sale",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="vendors.vendor",
                verbose_name="Sold By",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="warranty_period",
            field=models.CharField(
                blank=True,
                help_text="e.g. '12 months', '2 years manufacturer warranty'",
                max_length=100,
                verbose_name="Warranty Period",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight per unit in kilograms",
                max_digits=10,
                null=True,
                verbose_name="Unit Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Describe the image for accessibility",
                max_length=255,
                verbose_name="Image Description",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Order in gallery (0 = first)",
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="Upload product photo",
                upload_to="products/%Y/%m/",
                verbose_name="Image File",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Main image shown in listings",
                verbose_name="Primary Image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Uploaded On"),
        ),
    ]
