# Generated by Django 4.2.16 on 2026-04-21 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCertificationRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_details',
            field=models.CharField(blank=True, help_text='Packaging format, palletization, or bundle details', max_length=255, verbose_name='Packaging Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Threshold'),
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DATASHEET', 'Datasheet'), ('SAFETY', 'Safety Sheet'), ('WARRANTY', 'Warranty'), ('BROCHURE', 'Brochure'), ('INSTALLATION', 'Installation Guide'), ('OTHER', 'Other')], default='DATASHEET', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='products/documents/%Y/%m/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('certification_number', models.CharField(blank=True, default='', max_length=100)),
                ('issuing_body', models.CharField(blank=True, default='', max_length=255)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('verification_url', models.URLField(blank=True, default='')),
                ('document_url', models.URLField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_entries', to='catalog.product')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_entries', to='catalog.productcertificationregistry')),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('is_highlight', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_entries', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
