# Generated by Django 4.2.16 on 2026-04-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_catalog_uuid_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Initial Stock'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('IMPORT', 'CSV Import'), ('ORDER_COMMIT', 'Order Commit'), ('ORDER_RESTOCK', 'Order Restock')], max_length=32)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='catalog_pro_product_1f5840_idx'), models.Index(fields=['movement_type', 'created_at'], name='catalog_pro_movemen_d1a3e9_idx')],
            },
        ),
    ]
