# Generated by Django 4.2.16 on 2026-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=300, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productdocument',
            unique_together={('product', 'title')},
        ),
        migrations.AddConstraint(
            model_name='productcertification',
            constraint=models.UniqueConstraint(condition=models.Q(('registry__isnull', False)), fields=('product', 'registry'), name='unique_product_certification_registry'),
        ),
    ]
