# Generated by Django 4.2.16 on 2026-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BID', 'New Bid'), ('MILESTONE', 'Milestone Update'), ('PAYMENT', 'Payment Status'), ('ESCROW', 'Escrow Status'), ('DISPUTE', 'Dispute Update'), ('SYSTEM', 'System Alert'), ('CHAT', 'New Message')], default='SYSTEM', max_length=20),
        ),
    ]
