# Generated by Django 5.2.10 on 2026-01-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_buyer_confirmed_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
    ]
