# Generated by Django 4.2.16 on 2026-02-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteresponse',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='QuoteResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('availability_notes', models.TextField(blank=True)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.quoteitem')),
                ('quote_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.quoteresponse')),
            ],
        ),
    ]
