# Generated by Django 4.2.16 on 2026-02-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0005_location'),
        ('orders', '0004_alter_quoteresponse_delivery_fee_quoteresponseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='platform_settings.location'),
        ),
    ]
