# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options_alter_productimage_options_and_more"),
        ("orders", "0005_order_delivery_location"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
        ("vendors", "0006_vendor_location_text_alter_vendor_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Customer Order",
                "verbose_name_plural": "Customer Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteitem",
            options={
                "verbose_name": "Quote Item",
                "verbose_name_plural": "Quote Items",
            },
        ),
        migrations.AlterModelOptions(
            name="quoterequest",
            options={
                "verbose_name": "Price Quote Request",
                "verbose_name_plural": "Price Quote Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteresponse",
            options={
                "verbose_name": "Vendor Quote",
                "verbose_name_plural": "Vendor Quotes",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteresponseitem",
            options={
                "verbose_name": "Quote Line Item",
                "verbose_name_plural": "Quote Line Items",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer_confirmed_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Customer Confirmed Receipt"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ordered On"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="platform_settings.location",
                verbose_name="Delivery Location",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_delivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated Delivery Date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                default="UNPAID", max_length=20, verbose_name="Payment Status"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quote_response",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.quoteresponse",
                verbose_name="Based on Quote",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLACED", "🛒 Order Placed"),
                    ("CONFIRMED", "✅ Confirmed by Seller"),
                    ("PACKING", "📦 Being Prepared"),
                    ("SHIPPED", "🚚 Out for Delivery"),
                    ("DELIVERED", "📬 Delivered"),
                    ("COMPLETED", "✨ Completed"),
                    ("CANCELLED", "❌ Cancelled"),
                ],
                default="PLACED",
                max_length=20,
                verbose_name="Order Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total Amount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tracking Number"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="vendors.vendor",
                verbose_name="Sold By",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name_snapshot",
            field=models.CharField(
                max_length=255, verbose_name="Product Name (at time of order)"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price_snapshot",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Unit Price Paid"
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="quantity",
            field=models.IntegerField(verbose_name="Quantity Needed"),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="quote_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.quoterequest",
                verbose_name="Quote Request",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Requested By",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Requested On"),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "📤 Quote Requested"),
                    ("CONFIRMED", "✅ Quote Received"),
                    ("REJECTED", "❌ Request Declined"),
                ],
                default="REQUESTED",
                max_length=20,
                verbose_name="Request Status",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="confirmed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Quote Provided On"
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="confirmed_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Quoted Price"
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Delivery Fee",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Quote Expires On"),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="quote_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="orders.quoterequest",
                verbose_name="Original Request",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponse",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vendors.vendor",
                verbose_name="Quoted By",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponseitem",
            name="availability_notes",
            field=models.TextField(
                blank=True, verbose_name="Availability / Delivery Notes"
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponseitem",
            name="quote_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.quoteitem",
                verbose_name="Item",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponseitem",
            name="quote_response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.quoteresponse",
                verbose_name="Quote",
            ),
        ),
        migrations.AlterField(
            model_name="quoteresponseitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Unit Price"
            ),
        ),
    ]
