# Generated by Django 5.2.10 on 2026-01-31 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'taxonomy_type': 'PROJECT'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='taxonomy.category'),
        ),
    ]
