# Generated by Django 4.2.16 on 2026-02-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0005_location'),
        ('projects', '0002_project_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='project',
                    old_name='location',
                    new_name='location_text',
                ),
                migrations.AlterField(
                    model_name='project',
                    name='location_text',
                    field=models.CharField(blank=True, db_column='location', max_length=255, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='platform_settings.location'),
        ),
    ]
