# Generated by Django 5.2.10 on 2026-02-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0006_data_migration_locations"),
        ("projects", "0003_project_location_text_alter_project_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="platform_settings.country",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
