# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
        ("projects", "0004_project_country_project_formatted_address_and_more"),
        ("taxonomy", "0002_alter_category_options_alter_category_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentcommitment",
            options={
                "verbose_name": "Investment Commitment",
                "verbose_name_plural": "Investment Commitments",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "verbose_name": "Construction Project",
                "verbose_name_plural": "Construction Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectcontractlink",
            options={
                "verbose_name": "Project Contract Link",
                "verbose_name_plural": "Project Contract Links",
            },
        ),
        migrations.AlterModelOptions(
            name="projectrequirement",
            options={
                "verbose_name": "Project Requirement",
                "verbose_name_plural": "Project Requirements",
            },
        ),
        migrations.AlterModelOptions(
            name="projectupdate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project Update",
                "verbose_name_plural": "Project Updates",
            },
        ),
        migrations.AlterField(
            model_name="investmentcommitment",
            name="amount_committed",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Investment Amount"
            ),
        ),
        migrations.AlterField(
            model_name="investmentcommitment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Pledged On"),
        ),
        migrations.AlterField(
            model_name="investmentcommitment",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Investor",
            ),
        ),
        migrations.AlterField(
            model_name="investmentcommitment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commitments",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="investmentcommitment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLEDGED", "🤝 Investment Pledged"),
                    ("CONFIRMED", "✅ Funds Committed"),
                    ("CANCELLED", "❌ Cancelled"),
                ],
                default="PLEDGED",
                max_length=20,
                verbose_name="Commitment Status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"taxonomy_type": "PROJECT"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="taxonomy.category",
                verbose_name="Project Type",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="platform_settings.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Project Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="estimated_budget",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Estimated Total Budget"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="formatted_address",
            field=models.TextField(blank=True, verbose_name="Full Address"),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding_required",
            field=models.BooleanField(default=False, verbose_name="Seeking Investment"),
        ),
        migrations.AlterField(
            model_name="project",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="platform_settings.location",
                verbose_name="Location Details",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="location_text",
            field=models.CharField(
                blank=True,
                db_column="location",
                max_length=255,
                null=True,
                verbose_name="Project Location",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Owner",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("LISTED", "📋 Planning Phase"),
                    ("FUNDING_OPEN", "💰 Seeking Investment"),
                    ("EXECUTION_STARTED", "🏗️ Construction in Progress"),
                    ("COMPLETED", "✅ Project Complete"),
                ],
                default="LISTED",
                max_length=30,
                verbose_name="Project Status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Project Name"),
        ),
        migrations.AlterField(
            model_name="projectcontractlink",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_project",
                to="contracts.contract",
                verbose_name="Related Contract",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontractlink",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_contracts",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="projectrequirement",
            name="description",
            field=models.CharField(
                max_length=255, verbose_name="Specific Requirements"
            ),
        ),
        migrations.AlterField(
            model_name="projectrequirement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="projects.project",
                verbose_name="For Project",
            ),
        ),
        migrations.AlterField(
            model_name="projectrequirement",
            name="quantity",
            field=models.CharField(
                help_text="e.g. '500 Bags of Cement', '2 Teams of Masons'",
                max_length=100,
                verbose_name="Quantity / Scale",
            ),
        ),
        migrations.AlterField(
            model_name="projectrequirement",
            name="type",
            field=models.CharField(
                choices=[
                    ("MATERIAL", "📦 Building Materials"),
                    ("CONTRACTOR", "👷 Skilled Contractor"),
                    ("SERVICE", "🔧 Professional Service"),
                ],
                max_length=20,
                verbose_name="What's Needed",
            ),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Posted On"),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="posted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Posted By",
            ),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="update_text",
            field=models.TextField(verbose_name="Update Message"),
        ),
    ]
