# Generated by Django 4.2.16 on 2026-04-26 06:47

from django.db import migrations, models


def add_cover_photo_if_not_exists(apps, schema_editor):
    """Idempotently add cover_photo column if it doesn't already exist."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'projects_project'
              AND column_name = 'cover_photo'
        """)
        if cursor.fetchone():
            # Column already exists; mark state as applied only
            return

    Project = apps.get_model('projects', 'Project')
    field = models.ImageField(
        blank=True,
        null=True,
        upload_to='project_covers/%Y/%m/',
        verbose_name='Cover Photo'
    )
    field.set_attributes_from_name('cover_photo')
    schema_editor.add_field(Project, field)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_investmentcommitment_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_cover_photo_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='cover_photo',
                    field=models.ImageField(blank=True, null=True, upload_to='project_covers/%Y/%m/', verbose_name='Cover Photo'),
                ),
            ],
        ),
    ]
