# Generated by Django 5.2.10 on 2026-01-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_scope', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('BIDDING', 'Bidding'), ('AWARDED', 'Awarded'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
