# Generated by Django 4.2.16 on 2026-01-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('POSTED', 'Posted'), ('BIDDING', 'Bidding'), ('AWARDED', 'Awarded'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
