# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contract_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "verbose_name": "Work Contract",
                "verbose_name_plural": "Work Contracts",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="budget_max",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Maximum Budget"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="budget_min",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Minimum Budget"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Posted On"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="description_scope",
            field=models.TextField(
                help_text="Detailed description of the work required",
                verbose_name="Scope of Work",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Work Location"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Posted By",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Draft - Pending Review"),
                    ("POSTED", "📢 Posted - Accepting Bids"),
                    ("BIDDING", "🏆 Bidding in Progress"),
                    ("AWARDED", "🎯 Contractor Selected"),
                    ("IN_PROGRESS", "🏗️ Work in Progress"),
                    ("COMPLETED", "✅ Successfully Completed"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Contract Status",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Job Title"),
        ),
    ]
