# Generated by Django 5.2.10 on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
        ("taxonomy", "0003_category_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(
                choices=[
                    ("KES", "Kenyan Shilling"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                ],
                default="KES",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="bid_deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bid Submission Deadline"),
        ),
        migrations.AddField(
            model_name="contract",
            name="project_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Project Start Date"),
        ),
        migrations.AddField(
            model_name="contract",
            name="project_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Project Completion Date"),
        ),
        migrations.AddField(
            model_name="contract",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="taxonomy.category",
                verbose_name="Work Category",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="contract_images/%Y/%m/",
                verbose_name="Featured Image",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_terms",
            field=models.TextField(blank=True, verbose_name="Payment Terms"),
        ),
        migrations.AddField(
            model_name="contract",
            name="eligibility_criteria",
            field=models.TextField(blank=True, verbose_name="Eligibility Criteria"),
        ),
        migrations.CreateModel(
            name="ContractAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        upload_to="contract_attachments/%Y/%m/",
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("DRAWING", "Drawings"),
                            ("BOQ", "Bill of Quantities"),
                            ("SPEC", "Technical Specification"),
                            ("REPORT", "Site Report"),
                            ("PHOTO", "Site Photo"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Uploaded On")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contracts.contract",
                        verbose_name="Contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Attachment",
                "verbose_name_plural": "Contract Attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
