# Generated by Django 5.2.10 on 2026-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_procurement_fields_and_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="eligibility_criteria",
            field=models.TextField(
                blank=True,
                help_text="Minimum contractor class, experience, insurance requirements",
                verbose_name="Eligibility Criteria",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_terms",
            field=models.TextField(
                blank=True,
                help_text="e.g. '30% advance, 40% at midpoint, 30% on completion'",
                verbose_name="Payment Terms",
            ),
        ),
    ]
