# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
        ("disputes", "0001_initial"),
        ("orders", "0005_order_delivery_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispute",
            options={
                "verbose_name": "Dispute Case",
                "verbose_name_plural": "Dispute Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="evidencesubmission",
            options={
                "verbose_name": "Evidence Document",
                "verbose_name_plural": "Evidence Documents",
            },
        ),
        migrations.AlterField(
            model_name="dispute",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.contract",
                verbose_name="Related Contract",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Opened On"),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="opened_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opened_disputes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Opened By",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="Related Order",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="reason",
            field=models.TextField(
                help_text="Describe the issue in detail",
                verbose_name="Reason for Dispute",
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPENED", "🚨 Dispute Opened"),
                    ("UNDER_REVIEW", "🔍 Under Investigation"),
                    ("RESOLVED_RELEASE", "✅ Resolved - Release Funds"),
                    ("RESOLVED_REFUND", "↩️ Resolved - Refund Client"),
                    ("CLOSED", "📁 Case Closed"),
                ],
                default="OPENED",
                max_length=20,
                verbose_name="Case Status",
            ),
        ),
        migrations.AlterField(
            model_name="evidencesubmission",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="disputes.dispute",
                verbose_name="For Dispute",
            ),
        ),
        migrations.AlterField(
            model_name="evidencesubmission",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Explanation"),
        ),
        migrations.AlterField(
            model_name="evidencesubmission",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitted By",
            ),
        ),
        migrations.AlterField(
            model_name="evidencesubmission",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Submitted On"),
        ),
        migrations.AlterField(
            model_name="evidencesubmission",
            name="uploaded_file_url",
            field=models.URLField(blank=True, verbose_name="Document / Photo"),
        ),
    ]
