# Generated by Django 5.2.10 on 2026-01-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SAP', 'SAP'), ('ORACLE', 'Oracle'), ('QUICKBOOKS', 'QuickBooks')], max_length=20)),
                ('api_endpoint', models.URLField()),
                ('auth_credentials', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSystemSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('sync_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.erpconnector')),
            ],
        ),
    ]
