# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_investmentcommitment_options_and_more"),
        ("regulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentagreement",
            options={
                "verbose_name": "Investment Agreement",
                "verbose_name_plural": "Investment Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="investmenttransaction",
            options={
                "verbose_name": "Investment Transaction",
                "verbose_name_plural": "Investment Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="investorprofile",
            options={
                "verbose_name": "Investor Profile",
                "verbose_name_plural": "Investor Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="investorreport",
            options={
                "verbose_name": "Investor Report",
                "verbose_name_plural": "Investor Reports",
            },
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="agreement_terms_url",
            field=models.URLField(blank=True, verbose_name="Contract Document"),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Investment Amount"
            ),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investment_agreements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Investor",
            ),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to="projects.project",
                verbose_name="Investment In",
            ),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Signed"
            ),
        ),
        migrations.AlterField(
            model_name="investmentagreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "📝 Draft - Awaiting Signatures"),
                    ("SIGNED", "✏️ Signed by All Parties"),
                    ("FUNDED", "💰 Funds Transferred"),
                    ("CANCELLED", "❌ Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Agreement Status",
            ),
        ),
        migrations.AlterField(
            model_name="investmenttransaction",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="regulation.investmentagreement",
                verbose_name="Part of Agreement",
            ),
        ),
        migrations.AlterField(
            model_name="investmenttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="investmenttransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Transaction Date"
            ),
        ),
        migrations.AlterField(
            model_name="investmenttransaction",
            name="escrow_account_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Escrow Account (if used)"
            ),
        ),
        migrations.AlterField(
            model_name="investmenttransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("FUNDING", "💰 Investment Deposit"),
                    ("RELEASE", "💸 Funds Released to Project"),
                    ("RETURN", "↩️ Return of Investment"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="accreditation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Under Review"),
                    ("ACCREDITED", "✅ Accredited Investor"),
                    ("NONE", "📝 Not Accredited"),
                ],
                default="NONE",
                max_length=20,
                verbose_name="Investment Accreditation",
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Profile Created"
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="jurisdiction",
            field=models.CharField(
                default="Global", max_length=100, verbose_name="Country of Residence"
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Verification in Progress"),
                    ("VERIFIED", "✅ Identity Verified"),
                    ("REJECTED", "❌ Verification Failed"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Identity Verification",
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account Owner",
            ),
        ),
        migrations.AlterField(
            model_name="investorreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Report Date"),
        ),
        migrations.AlterField(
            model_name="investorreport",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prepared For",
            ),
        ),
        migrations.AlterField(
            model_name="investorreport",
            name="performance_summary",
            field=models.TextField(verbose_name="Performance Summary"),
        ),
        migrations.AlterField(
            model_name="investorreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="projects.project",
                verbose_name="For Project",
            ),
        ),
        migrations.AlterField(
            model_name="investorreport",
            name="report_period",
            field=models.CharField(
                help_text="e.g. 'Q1 2026', 'January 2026'",
                max_length=50,
                verbose_name="Reporting Period",
            ),
        ),
    ]
