# Generated by Django 5.2.10 on 2026-01-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('taxonomy_type', models.CharField(choices=[('MATERIAL', 'Material'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('PROPERTY', 'Property'), ('FINANCE', 'Finance'), ('GOVERNMENT', 'Government'), ('COMPLIANCE', 'Compliance')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('slug', 'taxonomy_type', 'region_code')},
            },
        ),
    ]
