# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="taxonomy.category",
                verbose_name="Parent Category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="region_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Region Code"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="URL Slug"),
        ),
        migrations.AlterField(
            model_name="category",
            name="taxonomy_type",
            field=models.CharField(
                choices=[
                    ("MATERIAL", "📦 Building Materials"),
                    ("SERVICE", "🔧 Professional Services"),
                    ("PROJECT", "🏗️ Project Types"),
                    ("PROPERTY", "🏠 Property Types"),
                    ("FINANCE", "💰 Financial Products"),
                    ("GOVERNMENT", "🏛️ Government Categories"),
                    ("COMPLIANCE", "📋 Compliance Types"),
                ],
                max_length=32,
                verbose_name="Category Type",
            ),
        ),
    ]
