# Generated by Django 5.2.10 on 2026-01-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('LAND', 'Land'), ('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('RENOVATION', 'Renovation')], max_length=20)),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoning_info', models.CharField(max_length=255)),
                ('build_ready', models.BooleanField(default=False)),
                ('utilities_available', models.JSONField(default=list)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='development_metadata', to='property.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_properties', to='projects.project')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_projects', to='property.propertylisting')),
            ],
        ),
    ]
