# Generated by Django 5.2.10 on 2026-02-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0006_data_migration_locations"),
        ("property", "0002_propertylisting_location_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="platform_settings.country",
            ),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
