# Generated by Django 4.2.16 on 2026-04-21 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0007_location_latitude_location_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_property_module_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='platform_settings.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='description',
            field=models.TextField(help_text='Detailed description of the property', verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='formatted_address',
            field=models.TextField(blank=True, verbose_name='Full Formatted Address'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='platform_settings.location', verbose_name='Specific Location'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='location_text',
            field=models.CharField(blank=True, db_column='location', max_length=255, null=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Property Owner'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='price_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated Price / Value'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Property Title'),
        ),
    ]
