# Generated by Django 4.2.16 on 2026-04-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertylisting_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('internal_area_unit', models.CharField(choices=[('SQM', 'Square Meters'), ('SQFT', 'Square Feet'), ('ACRE', 'Acre'), ('HECTARE', 'Hectare')], default='SQM', max_length=10)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_size_unit', models.CharField(choices=[('SQM', 'Square Meters'), ('SQFT', 'Square Feet'), ('ACRE', 'Acre'), ('HECTARE', 'Hectare')], default='SQM', max_length=10)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('renovation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing_state', models.CharField(blank=True, choices=[('UNFURNISHED', 'Unfurnished'), ('PART_FURNISHED', 'Part Furnished'), ('FURNISHED', 'Furnished'), ('FITTED', 'Fitted')], default='', max_length=20)),
                ('condition_rating', models.CharField(blank=True, choices=[('SHELL', 'Shell'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], default='', max_length=20)),
                ('energy_rating', models.CharField(blank=True, default='', max_length=20)),
                ('occupancy_status', models.CharField(blank=True, choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('OWNER_OCCUPIED', 'Owner Occupied'), ('TENANTED', 'Tenanted'), ('UNDER_CONSTRUCTION', 'Under Construction')], default='', max_length=30)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='property.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OPEN_HOUSE', 'Open House'), ('PRIVATE_SHOWING', 'Private Showing')], default='PRIVATE_SHOWING', max_length=20)),
                ('occurrence_type', models.CharField(choices=[('SINGLE', 'Single'), ('RECURRING', 'Recurring'), ('APPOINTMENT_ONLY', 'Appointment Only')], default='SINGLE', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=120)),
                ('recurrence_end_at', models.DateTimeField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('instructions', models.TextField(blank=True, default='')),
                ('virtual_tour_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='property.propertylisting')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_strategy', models.CharField(choices=[('FIXED', 'Fixed'), ('NEGOTIABLE', 'Negotiable'), ('PRICE_ON_APPLICATION', 'Price on Application'), ('PER_UNIT', 'Per Unit')], default='FIXED', max_length=25)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_area_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_unit', models.CharField(choices=[('SQM', 'Square Meters'), ('SQFT', 'Square Feet'), ('ACRE', 'Acre'), ('HECTARE', 'Hectare')], default='SQM', max_length=10)),
                ('service_charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('insurance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financing_notes', models.TextField(blank=True, default='')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_profile', to='property.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwnershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('ownership_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRUST', 'Trust'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='', max_length=20)),
                ('title_reference', models.CharField(blank=True, default='', max_length=255)),
                ('deed_reference', models.CharField(blank=True, default='', max_length=255)),
                ('has_liens', models.BooleanField(default=False)),
                ('lien_notes', models.TextField(blank=True, default='')),
                ('disclosure_notes', models.TextField(blank=True, default='')),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='UNVERIFIED', max_length=20)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_profile', to='property.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FLOOR_PLAN', 'Floor Plan'), ('DOCUMENT', 'Document'), ('VIRTUAL_TOUR', 'Virtual Tour')], default='IMAGE', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='property/media/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='property.propertylisting')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_highlighted', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='property.propertylisting')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
