# Generated by Django 4.2.16 on 2026-04-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_category_options_alter_category_active_and_more'),
        ('property', '0006_propertyspecification_propertyshowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='purpose',
            field=models.ForeignKey(blank=True, limit_choices_to={'taxonomy_type': 'PROPERTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_listings', to='taxonomy.category', verbose_name='Property Purpose'),
        ),
    ]
