# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
        ("milestones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "verbose_name": "Project Milestone",
                "verbose_name_plural": "Project Milestones",
            },
        ),
        migrations.AlterModelOptions(
            name="milestonepayment",
            options={
                "verbose_name": "Milestone Payment",
                "verbose_name_plural": "Milestone Payments",
            },
        ),
        migrations.AlterField(
            model_name="milestone",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Payment Amount"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="contracts.contract",
                verbose_name="Part of Contract",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="description",
            field=models.TextField(blank=True, verbose_name="What's to be Delivered"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="due_date",
            field=models.DateField(verbose_name="Expected Completion Date"),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "📋 Not Started"),
                    ("COMPLETED", "✅ Work Completed"),
                    ("APPROVED", "👍 Client Approved"),
                    ("PAID", "💰 Payment Released"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Milestone Status",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Milestone Name"),
        ),
        migrations.AlterField(
            model_name="milestonepayment",
            name="milestone",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="milestones.milestone",
                verbose_name="Milestone",
            ),
        ),
        migrations.AlterField(
            model_name="milestonepayment",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Payment Reference Number"
            ),
        ),
        migrations.AlterField(
            model_name="milestonepayment",
            name="release_status",
            field=models.CharField(
                default="PENDING", max_length=50, verbose_name="Payment Status"
            ),
        ),
    ]
