# Generated by Django 4.2.16 on 2026-02-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0005_location'),
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictender',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='platform_settings.location'),
        ),
    ]
