# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("government", "0002_publictender_location"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="publictender",
            options={
                "verbose_name": "Government Tender",
                "verbose_name_plural": "Government Tenders",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=255, verbose_name="Action Taken"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed By",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.TextField(verbose_name="Additional Details"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="government.publictender",
                verbose_name="Tender",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="When"),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="bid_deadline",
            field=models.DateTimeField(verbose_name="Bid Submission Deadline"),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Published On"),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="description",
            field=models.TextField(verbose_name="Project Details"),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="issuing_authority",
            field=models.CharField(max_length=255, verbose_name="Government Agency"),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenders",
                to="platform_settings.location",
                verbose_name="Project Location",
            ),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="status",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "📢 Just Published"),
                    ("OPEN", "✅ Accepting Bids"),
                    ("EVALUATION", "🔍 Evaluating Bids"),
                    ("AWARDED", "🏆 Contract Awarded"),
                    ("COMPLETED", "✅ Project Complete"),
                ],
                default="PUBLISHED",
                max_length=20,
                verbose_name="Tender Status",
            ),
        ),
        migrations.AlterField(
            model_name="publictender",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tender Title"),
        ),
    ]
