# Generated by Django 5.2.10 on 2026-01-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_cancellation_rate_vendor_categories_served_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
