# Generated by Django 4.2.16 on 2026-02-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0004_exchangerateconfig'),
        ('vendors', '0003_alter_vendor_options_vendor_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='platform_settings.country'),
        ),
    ]
