# Generated by Django 4.2.16 on 2026-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='formatted_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location_hierarchy',
            field=models.JSONField(blank=True, default=dict, help_text='Stores country, state, city, neighborhood etc.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provides_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
