# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_settings", "0007_location_latitude_location_longitude"),
        ("vendors", "0006_vendor_location_text_alter_vendor_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Material Supplier",
                "verbose_name_plural": "Material Suppliers",
            },
        ),
        migrations.AlterField(
            model_name="vendor",
            name="average_rating",
            field=models.FloatField(default=0.0, verbose_name="Customer Rating (1-5)"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="business_name",
            field=models.CharField(
                max_length=255, verbose_name="Company / Business Name"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="cancellation_rate",
            field=models.FloatField(
                default=0.0, verbose_name="Order Cancellation Rate (%)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="categories_served",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Product Categories Offered"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendors",
                to="platform_settings.country",
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joined On"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="delivery_radius_km",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Delivery Coverage (km)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="delivery_timeliness",
            field=models.FloatField(
                default=0.0, verbose_name="On-Time Delivery Score (%)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="formatted_address",
            field=models.TextField(blank=True, verbose_name="Full Address"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(
                default=0.0, verbose_name="Order Fulfillment Rate (%)"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendors",
                to="platform_settings.location",
                verbose_name="Business Location",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="location_hierarchy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores country, state, city, neighborhood etc.",
                verbose_name="Location Details",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="location_text",
            field=models.CharField(
                blank=True,
                db_column="location",
                help_text="Legacy location text",
                max_length=255,
                null=True,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="provides_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Offers Delivery Service"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="registration_number",
            field=models.CharField(
                max_length=100, verbose_name="Business Registration Number"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="total_reviews",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Customer Reviews"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account Owner",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="verified_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Awaiting Approval"),
                    ("APPROVED", "✅ Verified Partner"),
                    ("REJECTED", "❌ Not Approved"),
                    ("SUSPENDED", "🚫 Temporarily Suspended"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
    ]
