# Generated by Django 4.2.16 on 2026-04-26 11:33

from django.db import migrations, models


def add_metadata_if_not_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'payments_payment'
              AND column_name = 'metadata'
        """)
        if cursor.fetchone():
            return

    Payment = apps.get_model('payments', 'Payment')
    field = models.JSONField(blank=True, default=dict)
    field.set_attributes_from_name('metadata')
    schema_editor.add_field(Payment, field)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_metadata_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='metadata',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
