# Generated by Django 5.2.10 on 2026-02-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractorprofile",
            options={"ordering": ["-created_at"]},
        ),
    ]
