# Generated by Django 5.2.10 on 2026-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0003_contractorprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorprofile",
            name="service_radius_km",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
