# Generated by Django 5.2.10 on 2026-02-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0004_contractorprofile_service_radius_km"),
        ("platform_settings", "0006_data_migration_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractorprofile",
            name="operating_region",
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractors",
                to="platform_settings.country",
            ),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="location_text",
            field=models.CharField(
                blank=True, db_column="operating_region", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="contractorprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
