# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contractors", "0005_remove_contractorprofile_operating_region_and_more"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractorcertification",
            options={
                "verbose_name": "Professional Certification",
                "verbose_name_plural": "Professional Certifications",
            },
        ),
        migrations.AlterModelOptions(
            name="contractorprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Construction Professional",
                "verbose_name_plural": "Construction Professionals",
            },
        ),
        migrations.AlterField(
            model_name="contractorcertification",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="contractors.contractorprofile",
                verbose_name="Belongs To",
            ),
        ),
        migrations.AlterField(
            model_name="contractorcertification",
            name="document_type",
            field=models.CharField(max_length=100, verbose_name="Certificate Type"),
        ),
        migrations.AlterField(
            model_name="contractorcertification",
            name="document_url",
            field=models.URLField(verbose_name="Document Link"),
        ),
        migrations.AlterField(
            model_name="contractorcertification",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Verified by Admin"),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="company_name",
            field=models.CharField(
                max_length=255, verbose_name="Company / Business Name"
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractors",
                to="platform_settings.country",
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joined On"),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="formatted_address",
            field=models.TextField(blank=True, verbose_name="Full Address"),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractors",
                to="platform_settings.location",
                verbose_name="Business Location",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="location_text",
            field=models.CharField(
                blank=True,
                db_column="operating_region",
                max_length=255,
                null=True,
                verbose_name="Primary Work Area",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                verbose_name="Average Customer Rating",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="service_categories",
            field=models.JSONField(
                help_text="List of services offered, e.g. ['Masonry', 'Electrical', 'Plumbing']",
                verbose_name="Services Offered",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="service_radius_km",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Service Coverage Radius (km)"
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account Owner",
            ),
        ),
        migrations.AlterField(
            model_name="contractorprofile",
            name="verified_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Application Under Review"),
                    ("APPROVED", "✅ Verified Professional"),
                    ("REJECTED", "❌ Application Declined"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
    ]
