# Generated by Django 5.2.10 on 2026-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_carrier_deliveryzone_shipment_trackingevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryzone",
            name="center_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="center_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="per_volume_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="radius_km",
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name="shipment",
            name="external_tracking_id",
            field=models.CharField(
                blank=True, help_text="Carrier's internal tracking ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="service_level",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Delivery"),
                    ("EXPRESS", "Express Delivery"),
                    ("SAME_DAY", "Same Day Delivery"),
                ],
                default="STANDARD",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="volume",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Volume in M3", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Weight in KG", max_digits=10
            ),
        ),
    ]
