# Generated by Django 5.2.10 on 2026-02-21 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_deliveryzone_center_lat_deliveryzone_center_lng_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Base URL for the Courier's API"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Header: Authorization / X-API-Key",
                        max_length=255,
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True,
                        help_text="Used for signature generation if required",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Where we send updates TO the courier (optional)",
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret to validate incoming webhooks FROM courier",
                        max_length=255,
                    ),
                ),
                (
                    "create_order_endpoint",
                    models.CharField(
                        default="/orders",
                        help_text="POST endpoint to create shipment",
                        max_length=255,
                    ),
                ),
                (
                    "cancel_order_endpoint",
                    models.CharField(
                        default="/orders/cancel",
                        help_text="POST/DELETE endpoint to cancel",
                        max_length=255,
                    ),
                ),
                (
                    "track_order_endpoint",
                    models.CharField(
                        default="/track",
                        help_text="GET endpoint to fetch status",
                        max_length=255,
                    ),
                ),
                (
                    "field_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map internal fields to external API payload keys",
                    ),
                ),
                (
                    "status_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map external status codes to internal choices",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CourierDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LICENSE", "Transport License"),
                            ("INSURANCE", "Insurance Certificate"),
                            ("REGISTRATION", "Business Registration"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="courier_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=100)),
                ("tax_pin", models.CharField(blank=True, max_length=50)),
                ("support_email", models.EmailField(max_length=254)),
                ("support_phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum cost for this zone",
                        max_digits=10,
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=10
                    ),
                ),
                (
                    "per_kg_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "express_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "same_day_multiplier",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="logistics.courierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("POLYGON", "Polygon Area"),
                            ("RADIUS", "Radius Circle"),
                        ],
                        default="RADIUS",
                        max_length=20,
                    ),
                ),
                ("center_lat", models.FloatField(blank=True, null=True)),
                ("center_lng", models.FloatField(blank=True, null=True)),
                ("radius_km", models.FloatField(default=10.0)),
                (
                    "geometry",
                    models.JSONField(
                        blank=True,
                        help_text="GeoJSON Polygon if type is Polygon",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_zones",
                        to="logistics.courierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Incoming"), ("OUT", "Outgoing")], max_length=10
                    ),
                ),
                ("url", models.URLField()),
                ("payload", models.JSONField()),
                ("response_code", models.IntegerField(null=True)),
                ("response_body", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.courierprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="DeliveryZone",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="carrier",
            name="webhook_secret",
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.carrier",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="external_tracking_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="service_level",
            field=models.CharField(default="STANDARD", max_length=50),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="volume",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="courierdocument",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="logistics.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="courierapiconfig",
            name="courier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_config",
                to="logistics.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_carrier",
                to="logistics.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="pricingrule",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="logistics.pricingzone",
            ),
        ),
    ]
