# Generated by Django 5.2.10 on 2026-02-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_courierapiconfig_courierdocument_courierprofile_and_more"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="couriers",
                to="platform_settings.country",
            ),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="formatted_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="couriers",
                to="platform_settings.location",
            ),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="location_text",
            field=models.CharField(
                blank=True,
                help_text="Operational base city or region",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="courierprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
    ]
