# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_courierprofile_country_and_more"),
        ("orders", "0005_order_delivery_location"),
        ("platform_settings", "0007_location_latitude_location_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrier",
            options={
                "verbose_name": "Legacy Carrier",
                "verbose_name_plural": "Legacy Carriers",
            },
        ),
        migrations.AlterModelOptions(
            name="courierapiconfig",
            options={
                "verbose_name": "Courier API Configuration",
                "verbose_name_plural": "Courier API Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="courierdocument",
            options={
                "verbose_name": "Courier Document",
                "verbose_name_plural": "Courier Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="courierprofile",
            options={
                "verbose_name": "Logistics Partner",
                "verbose_name_plural": "Logistics Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingrule",
            options={
                "verbose_name": "Pricing Rule",
                "verbose_name_plural": "Pricing Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingzone",
            options={
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
            },
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Shipment", "verbose_name_plural": "Shipments"},
        ),
        migrations.AlterModelOptions(
            name="trackingevent",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
            },
        ),
        migrations.AlterModelOptions(
            name="webhooklog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
            },
        ),
        migrations.AlterField(
            model_name="carrier",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Carrier Code"
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Carrier Name"),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_carrier",
                to="logistics.courierprofile",
                verbose_name="Linked Courier Profile",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Header: Authorization / X-API-Key",
                max_length=255,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="api_secret",
            field=models.CharField(
                blank=True,
                help_text="Used for signature generation if required",
                max_length=255,
                verbose_name="API Secret",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="base_url",
            field=models.URLField(
                help_text="Base URL for the Courier's API", verbose_name="API Base URL"
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="cancel_order_endpoint",
            field=models.CharField(
                default="/orders/cancel",
                help_text="POST/DELETE endpoint to cancel",
                max_length=255,
                verbose_name="Cancel Order Endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="courier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_config",
                to="logistics.courierprofile",
                verbose_name="For Courier",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="create_order_endpoint",
            field=models.CharField(
                default="/orders",
                help_text="POST endpoint to create shipment",
                max_length=255,
                verbose_name="Create Order Endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="field_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map internal fields to external API payload keys",
                verbose_name="Field Mapping",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="status_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map external status codes to internal choices",
                verbose_name="Status Code Mapping",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="track_order_endpoint",
            field=models.CharField(
                default="/track",
                help_text="GET endpoint to fetch status",
                max_length=255,
                verbose_name="Track Order Endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret to validate incoming webhooks FROM courier",
                max_length=255,
                verbose_name="Incoming Webhook Secret",
            ),
        ),
        migrations.AlterField(
            model_name="courierapiconfig",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Where we send updates TO the courier (optional)",
                verbose_name="Our Webhook to Courier",
            ),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin Review Notes"),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="logistics.courierprofile",
                verbose_name="Belongs To",
            ),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("LICENSE", "🚛 Transport License"),
                    ("INSURANCE", "🛡️ Insurance Certificate"),
                    ("REGISTRATION", "📄 Business Registration"),
                    ("OTHER", "📎 Other Document"),
                ],
                max_length=20,
                verbose_name="Document Type",
            ),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Document Expires On"
            ),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="file",
            field=models.FileField(
                upload_to="courier_docs/", verbose_name="Document File"
            ),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verified by Admin"),
        ),
        migrations.AlterField(
            model_name="courierdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Uploaded On"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="couriers",
                to="platform_settings.country",
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Joined On"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="formatted_address",
            field=models.TextField(blank=True, verbose_name="Full Address"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Active for Deliveries"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="couriers",
                to="platform_settings.location",
                verbose_name="Business Location",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="location_text",
            field=models.CharField(
                blank=True,
                help_text="Operational base city or region",
                max_length=255,
                null=True,
                verbose_name="Primary Operating Region",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="logo_url",
            field=models.URLField(blank=True, verbose_name="Company Logo"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=12,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="registration_number",
            field=models.CharField(
                max_length=100, verbose_name="Business Registration Number"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Reason (if rejected)"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Review Completed On"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "📝 Draft - Incomplete"),
                    ("PENDING", "⏳ Awaiting Review"),
                    ("UNDER_REVIEW", "🔍 Under Review"),
                    ("APPROVED", "✅ Verified Partner"),
                    ("REJECTED", "❌ Application Declined"),
                    ("SUSPENDED", "🚫 Account Suspended"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Application Submitted On"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="support_email",
            field=models.EmailField(
                max_length=254, verbose_name="Customer Support Email"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="support_phone",
            field=models.CharField(
                max_length=20, verbose_name="Customer Support Phone"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="tax_pin",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Tax PIN / VAT Number"
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account Owner",
            ),
        ),
        migrations.AlterField(
            model_name="courierprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Company Website"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="base_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Minimum cost for this zone",
                max_digits=10,
                verbose_name="Base Delivery Fee",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_rules",
                to="logistics.courierprofile",
                verbose_name="For Courier",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="express_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                max_digits=4,
                verbose_name="Express Delivery Multiplier",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="max_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                max_digits=10,
                verbose_name="Maximum Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="min_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Minimum Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="per_kg_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Price per kg",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="same_day_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                max_digits=4,
                verbose_name="Same-Day Delivery Multiplier",
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="logistics.pricingzone",
                verbose_name="Delivery Zone",
            ),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="center_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Center Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="center_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Center Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_zones",
                to="logistics.courierprofile",
                verbose_name="For Courier",
            ),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="description",
            field=models.TextField(blank=True, verbose_name="Zone Description"),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="geometry",
            field=models.JSONField(
                blank=True,
                help_text="GeoJSON Polygon if type is Polygon",
                null=True,
                verbose_name="Zone Geometry",
            ),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Zone Name"),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="radius_km",
            field=models.FloatField(default=10.0, verbose_name="Radius (km)"),
        ),
        migrations.AlterField(
            model_name="pricingzone",
            name="zone_type",
            field=models.CharField(
                choices=[
                    ("POLYGON", "📍 Custom Area (Polygon)"),
                    ("RADIUS", "⭕ Radius Circle"),
                ],
                default="RADIUS",
                max_length=20,
                verbose_name="Zone Type",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.carrier",
                verbose_name="Carrier",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.courierprofile",
                verbose_name="Logistics Partner",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="current_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="current_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Actually Delivered On"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="destination_address",
            field=models.TextField(verbose_name="Delivery Address"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="expected_delivery",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expected Delivery"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="external_tracking_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Carrier Tracking ID"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="last_location_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Location Last Updated"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment",
                to="orders.order",
                verbose_name="For Order",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="origin_address",
            field=models.TextField(verbose_name="Pickup Address"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="recipient_name",
            field=models.CharField(max_length=255, verbose_name="Recipient Name"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="recipient_phone",
            field=models.CharField(max_length=20, verbose_name="Recipient Phone"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="service_level",
            field=models.CharField(
                default="STANDARD", max_length=50, verbose_name="Service Level"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "📦 Awaiting Pickup"),
                    ("IN_TRANSIT", "🚚 In Transit"),
                    ("OUT_FOR_DELIVERY", "🏃 Out for Delivery"),
                    ("DELIVERED", "✅ Delivered"),
                    ("FAILED", "❌ Delivery Failed"),
                    ("RETURNED", "↩️ Returned to Sender"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Shipment Status",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Tracking Number"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="volume",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Package Volume (m³)",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Package Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="description",
            field=models.TextField(verbose_name="Details"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="GPS Latitude"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="GPS Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="raw_payload",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Raw Data (for debugging)"
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="logistics.shipment",
                verbose_name="Shipment",
            ),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Status Update"),
        ),
        migrations.AlterField(
            model_name="trackingevent",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="When"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics.courierprofile",
                verbose_name="Courier",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="direction",
            field=models.CharField(
                choices=[("IN", "⬇️ Incoming"), ("OUT", "⬆️ Outgoing")],
                max_length=10,
                verbose_name="Direction",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="payload",
            field=models.JSONField(verbose_name="Payload"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="response_body",
            field=models.TextField(blank=True, verbose_name="Response Body"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="response_code",
            field=models.IntegerField(null=True, verbose_name="Response Code"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="success",
            field=models.BooleanField(default=False, verbose_name="Successful"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="When"),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
