# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
        ("disputes", "0002_alter_dispute_options_and_more"),
        ("escrow", "0001_initial"),
        ("milestones", "0002_alter_milestone_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escrowaccount",
            options={
                "verbose_name": "Escrow Account",
                "verbose_name_plural": "Escrow Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="escrowhold",
            options={
                "verbose_name": "Payment Hold",
                "verbose_name_plural": "Payment Holds",
            },
        ),
        migrations.AlterModelOptions(
            name="escrowrelease",
            options={
                "verbose_name": "Fund Release",
                "verbose_name_plural": "Fund Releases",
            },
        ),
        migrations.AlterModelOptions(
            name="escrowtransaction",
            options={
                "verbose_name": "Escrow Transaction",
                "verbose_name_plural": "Escrow Transactions",
            },
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrow_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funded By",
            ),
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrow_account",
                to="contracts.contract",
                verbose_name="For Contract",
            ),
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="currency",
            field=models.CharField(
                default="USD", max_length=10, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "🔒 Funds Secured"),
                    ("RELEASED", "✅ Funds Released"),
                    ("CLOSED", "📁 Account Closed"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="escrowaccount",
            name="total_amount_held",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Amount in Escrow",
            ),
        ),
        migrations.AlterField(
            model_name="escrowhold",
            name="dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="disputes.dispute",
                verbose_name="Related Dispute",
            ),
        ),
        migrations.AlterField(
            model_name="escrowhold",
            name="escrow_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holds",
                to="escrow.escrowaccount",
                verbose_name="Escrow Account",
            ),
        ),
        migrations.AlterField(
            model_name="escrowhold",
            name="reason",
            field=models.TextField(verbose_name="Reason for Hold"),
        ),
        migrations.AlterField(
            model_name="escrowhold",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "🚫 On Hold"), ("LIFTED", "✅ Hold Removed")],
                default="ACTIVE",
                max_length=20,
                verbose_name="Hold Status",
            ),
        ),
        migrations.AlterField(
            model_name="escrowrelease",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AlterField(
            model_name="escrowrelease",
            name="milestone",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrow_release",
                to="milestones.milestone",
                verbose_name="For Milestone",
            ),
        ),
        migrations.AlterField(
            model_name="escrowrelease",
            name="release_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "⏳ Awaiting Approval"),
                    ("COMPLETED", "✅ Released"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Release Status",
            ),
        ),
        migrations.AlterField(
            model_name="escrowrelease",
            name="released_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Amount Released"
            ),
        ),
        migrations.AlterField(
            model_name="escrowrelease",
            name="released_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Released On"
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Transaction Date"
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="escrow_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="escrow.escrowaccount",
                verbose_name="Escrow Account",
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="milestones.milestone",
                verbose_name="Related Milestone",
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Payment Reference"
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "💰 Fund Deposit"),
                    ("RELEASE", "💸 Fund Release"),
                    ("REFUND", "↩️ Refund to Client"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
    ]
