#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/deploy-prod.sh <public-domain> [--config]

Examples:
  scripts/deploy-prod.sh marketplace.example.com --config
  scripts/deploy-prod.sh marketplace.example.com

The script generates missing production variables for the current process:
  PUBLIC_DOMAIN
  POSTGRES_PASSWORD
  DJANGO_SECRET_KEY

It does not create or require a .env file. For local Docker deployments, it
  persists generated values in .deploy/prod-vars.sh so redeploys and follow-up
  docker compose commands reuse the same domain, database password, and Django
  secret.

Optional environment overrides:
  POSTGRES_PASSWORD      Use an existing database password instead of generating one.
  DJANGO_SECRET_KEY      Use an existing Django secret instead of generating one.
  POSTGRES_DB            Defaults to marketplace.
  POSTGRES_USER          Defaults to postgres.
  DATABASE_URL           Use an external database URL instead of the Docker Postgres URL.
  ALLOWED_HOSTS          Override the domain-derived host list.
  CORS_ALLOWED_ORIGINS   Override the domain-derived HTTPS origin.
  CSRF_TRUSTED_ORIGINS   Override the domain-derived HTTPS origin.
  VITE_API_URL           Override https://PUBLIC_DOMAIN/api.
  VITE_WS_URL            Override wss://PUBLIC_DOMAIN/ws/notifications/.
USAGE
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32 | tr -d '\n'
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
  fi
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || $# -lt 1 ]]; then
  usage
  exit 0
fi

PUBLIC_DOMAIN="$1"
MODE="${2:---deploy}"

if [[ "$MODE" != "--deploy" && "$MODE" != "--config" ]]; then
  echo "Unknown mode: $MODE" >&2
  usage >&2
  exit 2
fi

SECRETS_DIR=".deploy"
SECRETS_FILE="$SECRETS_DIR/prod-vars.sh"

if [[ -f "$SECRETS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
fi

export PUBLIC_DOMAIN
POSTGRES_PASSWORD_WAS_PROVIDED="${POSTGRES_PASSWORD:+1}"
DJANGO_SECRET_KEY_WAS_PROVIDED="${DJANGO_SECRET_KEY:+1}"

if [[ -z "${POSTGRES_PASSWORD:-}" || -z "${DJANGO_SECRET_KEY:-}" || "${PUBLIC_DOMAIN:-}" != "${1:-}" ]]; then
  mkdir -p "$SECRETS_DIR"
  chmod 700 "$SECRETS_DIR"

  export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(random_secret)}"
  export DJANGO_SECRET_KEY="${DJANGO_SECRET_KEY:-$(random_secret)}"

  {
    printf "# Generated by scripts/deploy-prod.sh. Do not commit.\n"
    printf "export PUBLIC_DOMAIN=%q\n" "$PUBLIC_DOMAIN"
    printf "export POSTGRES_PASSWORD=%q\n" "$POSTGRES_PASSWORD"
    printf "export DJANGO_SECRET_KEY=%q\n" "$DJANGO_SECRET_KEY"
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
else
  export POSTGRES_PASSWORD
  export DJANGO_SECRET_KEY
fi

echo "Production variables prepared for $PUBLIC_DOMAIN"
echo "PUBLIC_DOMAIN=$PUBLIC_DOMAIN"
echo "POSTGRES_DB=${POSTGRES_DB:-marketplace}"
echo "POSTGRES_USER=${POSTGRES_USER:-postgres}"
echo "POSTGRES_PASSWORD=<from environment or $SECRETS_FILE>"
echo "DJANGO_SECRET_KEY=<from environment or $SECRETS_FILE>"
echo "Postgres will create the database automatically on first container boot if the postgres volume is empty."

if [[ "$MODE" == "--config" ]]; then
  echo "Validating production Compose config..."
  COMPOSE_DISABLE_ENV_FILE=1 docker compose -f docker-compose.yml -f docker-compose.prod.yml config --quiet
  echo "Production Compose config is valid."
else
  if [[ -z "$POSTGRES_PASSWORD_WAS_PROVIDED" || -z "$DJANGO_SECRET_KEY_WAS_PROVIDED" ]]; then
    echo "Generated secrets were saved to $SECRETS_FILE for repeatable redeploys."
    echo "Back up this file or move these values into your deployment platform's secret store before relying on this server long term."
  fi
  echo "Starting production stack..."
  COMPOSE_DISABLE_ENV_FILE=1 docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
fi
