#!/usr/bin/env bash

DEFAULT_PUBLIC_DOMAIN="${DEFAULT_PUBLIC_DOMAIN:-paanguzo.iqsaccodigital.com}"
SECRETS_DIR="${SECRETS_DIR:-.deploy}"
SECRETS_FILE="${SECRETS_FILE:-$SECRETS_DIR/prod-vars.sh}"

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32 | tr -d '\n'
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
  fi
}

load_prod_env() {
  local requested_domain="${1:-$DEFAULT_PUBLIC_DOMAIN}"

  if [[ -f "$SECRETS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$SECRETS_FILE"
  fi

  export PUBLIC_DOMAIN="${requested_domain:-${PUBLIC_DOMAIN:-$DEFAULT_PUBLIC_DOMAIN}}"
  export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(random_secret)}"
  export DJANGO_SECRET_KEY="${DJANGO_SECRET_KEY:-$(random_secret)}"

  # Keep generated database passwords URL-safe because DATABASE_URL embeds them.
  if ! printf "%s" "$POSTGRES_PASSWORD" | grep -Eq '^[A-Za-z0-9]+$'; then
    export POSTGRES_PASSWORD="$(random_secret)"
  fi
}

write_prod_env() {
  mkdir -p "$SECRETS_DIR"
  chmod 700 "$SECRETS_DIR"

  {
    printf "# Generated by deployment scripts. Do not commit.\n"
    printf "export PUBLIC_DOMAIN=%q\n" "$PUBLIC_DOMAIN"
    printf "export POSTGRES_PASSWORD=%q\n" "$POSTGRES_PASSWORD"
    printf "export DJANGO_SECRET_KEY=%q\n" "$DJANGO_SECRET_KEY"
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
}
