# Generated by Django 5.2.10 on 2026-01-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AML_SAR', 'Suspicious Activity Report'), ('TAX_VAT', 'VAT Filing'), ('AUDIT_LOG', 'Audit Log')], max_length=20)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='GENERATED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('filing_reference', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
            ],
        ),
    ]
