# Generated by Django 5.2.10 on 2026-03-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0001_initial"),
        ("contractors", "0005_remove_contractorprofile_operating_region_and_more"),
        ("contracts", "0003_alter_contract_options_alter_contract_budget_max_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "verbose_name": "Contractor Bid",
                "verbose_name_plural": "Contractor Bids",
            },
        ),
        migrations.AlterField(
            model_name="bid",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="contracts.contract",
                verbose_name="For Contract",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="contractors.contractorprofile",
                verbose_name="Submitted By",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Submitted On"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="message",
            field=models.TextField(blank=True, verbose_name="Cover Letter / Proposal"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="proposed_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Proposed Price"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="proposed_timeline_days",
            field=models.IntegerField(verbose_name="Estimated Timeline (days)"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "📤 Bid Submitted"),
                    ("SHORTLISTED", "⭐ Shortlisted"),
                    ("REJECTED", "❌ Not Selected"),
                    ("AWARDED", "🏆 Bid Won!"),
                ],
                default="SUBMITTED",
                max_length=20,
                verbose_name="Bid Status",
            ),
        ),
    ]
